### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#106]
Minor suggested documentation improvements:

- Indicate that ONLY draw.io online can use the required plugin svgdata.js. The desktop version will load it but not use it, no longer supported.
- In the getting started section include a link to the example and more explanation for the compound feature (ex. how it uses multiple objets)
- Explicitely state that multiple metrics cannot be defined for a cell
- Explicitely state that you cannot define multiple cell rules with the same name
- Simple validation method for images: Maybe suggest users cut and paste their image into a browser web developer console inspect and provide a screenshot of what is expected. Just to confirm they have valid object ids!

**Comment by andymchugh** [comment]
I just checked the first bullet because that would have been really sad. On windows I pulled in the latest draw.io app version v24.7.8. I removed the svgdata plugin. I added the svgdata plugin. I edited an svg and the saved svg displays fine.

All I can think is you didn't restart draw.io after adding the plugin. It works fine and if anything the online version is now more closely resembling the desktop version wrt how the plugins work.

**Comment by xkilian** [comment]
Hmm. Strange. Maybe it is because I am not admin (corporate laptop), maybe something is not registering correctly. I did restart it. It caused me quite a bit of grief, maybe indicate in the docs that when starting a new diagram, check that the objects are displayed. I tried different versions on my windows 10 desktop.

**Comment by andymchugh** [comment]
I've added a feature exploration section. compound drive is now documented there. There's also a troubleshooting faq section that can grow over time.

https://github.com/andymchugh/andrewbmchugh-flow-panel/tree/main/src#feature-exploration
