### ISSUE TITLE
Feature Request: Animate svg cell-ids (e.g. changing size)

### ISSUE THREAD

**Issue by fjkbit** [andymchugh/andrewbmchugh-flow-panel#40]
Hi, 
in the old flowcharting panel there was the option to animate your svg.
e.g. displaying filling levels of a tank or vessel by changing the height of an form based on your data. 

So far I didn't see the option to animate your svgs yet. Any plans to integrate this in your .yaml?

Thanks for your info!

**Comment by andymchugh** [comment]
I'm not planning to add general animation support at the moment. I added the draw.io flowAnimation as a unique drive because you get it in draw.io just by selecting a check box.

But I could add a general purpose dom-element-attribute drive if that's wanted. i.e. changing the dimensions of a rect, circle, etc. based off of timeseries.

In yaml, was thinking about doing that based off of cell-id->elementType->attribute. i.e. on cell-abc (which identifies a dom element tree),  drive elemetType='rect', attribute='width' based off of data. It sounds like that could give you the 'fill' levels you describe whilst keeping the panel ignorant of the content. As the attribute has to pre-exist this would also be compatible with the dompurify step that's done prior to adjustments. Would that be useful to you?

**Comment by fjkbit** [comment]
This sounds like a plan. I'd have to manipulate my query a bit to get the relation right but in general this could work. 
Thanks for your quick response and your dev dedication!

**Comment by andymchugh** [comment]
OK, great. Will get this done.

**Comment by andymchugh** [comment]
When I looked into this there was a way to do fill levels leveraging clip-path, so I've added a fillLevel drive that under the hood leverages clip-path. With this change you don't get the ability to adjust anything's size, but you do get the ability to apply a fill-level to pretty much any shape, including shapes drawn with lines via 'path'. See [yaml_defs](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/yaml_defs/panelConfig.yaml#L264) for the config change.

This is now landed and will be in the next build. Can you confirm (conceptually) this meets your ask?

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/144024509/c13f7c70-372d-4557-b292-454db9a69209)

**Comment by fjkbit** [comment]
Hi Andy, 
This is actually a pretty nice Solution and absolutely a legit way for my Problem. last time I did a workaround with multiple elements. This wont be needed now. 
Thanks for implementing this! When are you planning to publishing your built? 
Kind regards

**Comment by andymchugh** [comment]
great :). It should be out in a week or two.

**Comment by andymchugh** [comment]
This is now published as part of 1.13.0.

There's a [demonstration dashboard](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboards/fillLevel.json)

and the corresponding [svg](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/fillLevel.svg)

and the corresponding [yaml](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/fillLevel.yaml)

**Comment by fjkbit** [comment]
Hi I just wanted to give you feedback, that your implementation works perfectly once you get the hang of it! 
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/135625409/a770720d-7be6-4446-8197-a2b744fd6bf7)
Thanks for your dedication for this plugin! This gives so many visualization options!

**Comment by andymchugh** [comment]
Great 🙂.  Thanks for the feedback
