### ISSUE TITLE
Feature request: Graph tooltip and link cell-id to more than one timeseries

### ISSUE THREAD

**Issue by erlfos** [andymchugh/andrewbmchugh-flow-panel#53]
Hi
This looks like a great replacement for the FlowCharting plugin when it becomes obsolete. A couple of things that I miss from the FlowCharting plugin are:

1. The possiblity to have a visible graph of the time series in the tooltip
2. The possibility to have a cell referencing more than one time series

The last point is very useful to show how one service may be dependent on several metrics\KPIs. I have added an image to show how we use FlowCharting today. In FlowCharting you have rules, and each rule may be applied to several cell-ids. For example, one rule is applied to each of the cells marked in red. The chart is supposed to show how a service on the top of the chart is dependent on several metrics and network elements below, so if one metric is below a threshold it will show what is affected. I have tried to make this work in the Flow plugin, but I don't think it is possible right now?
You can also see the graph tooltip which is useful.
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/45815831/e91f40e4-41ed-4a7f-9ddb-2661dbdbaf2a)

**Comment by madansu** [comment]
Upvoting this feature !

**Comment by andymchugh** [comment]
On the tooltip point, this isn't likely to happen any time soon because of a whole bunch of reasons:

- The flowcharting panel had a lot of code and dependencies to implement this. It's not a small thing to do.
- Although I had it enabled and loved seeing it pop up when using the flowcharting panel, when I thought back on it over the years I don't think it ever actually told me anything. The problem was the color only reflected the current value and their was no Y scale. So timeseries moving between say 390 and 410 looked the same as between 100 and 700. The only way to understand the data was to actually dive off and look at it in a proper time-series panel. Maybe I was using it wrong, but that was my experience of it.
- Grafana have something very similar on some of their plugins called spark-lines. But the last time I looked the api wasn't public so there is no way to leverage it. 
- This panel offers a time-slider so you do have an alternative way to see the data over time.

Given all of those things, the most likely way forward would be to leverage the spark-line api if Grafana made it available. 


Regarding the multiple metrics on a cell, it doesn't really fit with the way the panel works or the yaml is laid out. I get that the flowcharting panel laid out its data in a way that offered it, but for me the only time I came across it and had two readouts on a cell was when I'd made a mistake and had to go back in and try and fix it. That said, if you want two readouts within a cell it's easy to set up. You just have to add another text cell on top and drive it. You can even group them in draw.io to make it easy to drag them around.

I accept that separate cells wouldn't then support a combo popup showing three graphs like in your picture. But it's pretty unlikely the grafana spark-line api (if made public) would support that anyway...

So overall I'd say for now it's a 'No'. But if you are blocked from doing multiple readouts via multiple cells, can you go into some detail on it?

**Comment by erlfos** [comment]
Your time-slider is very useful, so I can accept that as way of seeing data over time. We usually show percentage based KPIs (success rate\failure rate) in our FlowCharting panels, so you know that the Y scale is 0-100. Lets hope that Grafana will open their spark line API some time in the future.

I am not sure if i understood this:

> if you want two readouts within a cell it's easy to set up. You just have to add another text cell on top and drive it.

What I want to accomplish is to show how "Service X" is dependent on "KPI A", "KPI B" and "KPI C", so that if all three KPIs are within the "green" threshold, "Service X" should be green, but if, say "KPI B" is in the "yellow" threshold area, "Service X" should be  yellow. Is there a way to do this in the Flow plugin?

**Comment by andymchugh** [comment]
Interesting what you say about 0-100 Y scales showing correctly. All of my metrics have larger ranges and I found the Y scale would auto adjust based on data. So in your example, if the data went from 70 to 95 over the time window, the Y scale would adjust to be 70 to 95. But maybe that auto adjustment kicks in at a certain point and a 0-100 range is always ok.

To your last question, no, there isn't a way to drive a fillColor by combining incoming data-series. But that is being discussed in https://github.com/andymchugh/andrewbmchugh-flow-panel/issues/48. So we could close this as a duplicate if that's all we have left in this issue?

**Comment by erlfos** [comment]
Yes, we can close this then.
