### ISSUE TITLE
Feature request: updating label text

### ISSUE THREAD

**Issue by jstaffans-relex** [andymchugh/andrewbmchugh-flow-panel#60]
Thanks for developing this plugin!

Would it be possible to enable updates of label texts in addition to colouring? I am thinking of an equivalent to the Grafana "Stat" panel type which can be configured to render the time series "name" instead of its value. The name is equivalent to whatever the query result legend is configured to be. The time series value will only be used for the panel colour.

![Screenshot 2024-05-28 at 11 08 31](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/118814862/fe5af7df-9635-4c3d-aa1b-005abe06b2c9)

**Comment by andymchugh** [comment]
There's two similar ways you can achieve this with todays version:
- you can enter the label as you want it in the svg and then not drive it from yaml.
- you can map the value to a string using valueMappings. With valueMappings both the min and max in the range are optional so you could map all values to the text of your choice.
```
  - valueMappings:
    - {text: "my name"}
```

Just wanted to confirm you'd thought of both of these and if so, what you see as the problem with either of these alternatives?

**Comment by andymchugh** [comment]
As of 1.12 [string data](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/CHANGELOG.md#string-data) can be applied to labels. So if your term is dynamic (changing with query refresh and time) having a text time-series would be the way to go.

I'm still trying to understand what about the legend would be dynamic because time-series in this space are essentially named off of the legend. I'm not yet seeing how that could change from refresh to refresh and still map to a cell.

I'm missing something. Could you explain why a text time-series isn't what you are after?

**Comment by jstaffans-relex** [comment]
Another option that would also work for my use case would be if it'd be possible to use a dashboard template variable to set the label text. That is probably easier to implement as well.

**Comment by jstaffans-relex** [comment]
>  Can you attach a screenshot of what your data query response looks like as that will help me look for the right stuff?

Attaching the query result JSON response for this query:

<img width="839" alt="Screenshot 2024-05-28 at 23 05 01" src="https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/118814862/e8e468f3-9df1-4bfe-9132-757b5cda2229">

[query.json](https://github.com/andymchugh/andrewbmchugh-flow-panel/files/15475457/query.json)

in this example I might want to render for example the `instance` label in the SVG box.

**Comment by andymchugh** [comment]
the panel uses grafana dataFrames to bring the myriad of different data sources into a common format and then uses getFieldDisplayName to decide the name of a series that then gets offered up to our yaml dataRef. See 
 https://grafana.com/developers/plugin-tools/create-a-plugin/develop-a-plugin/work-with-data-frames

When I look at your query result, my gut reaction is that getFieldDisplayName  would be returning up_result as the dataRef name.

I can understand why you'd like other parameters from your query to be available but nothing is jumping out as a way to do this. Certainly looking at random bits of the results query isn't going to happen because it would be a maintenance nightmare.

Dashboard template variables also doesn't sound 'central' to what this panel is about. At some point we've got to draw a line between what's possible and what's maintainable.

This really feels like you want some kind of table plugin to display the rows of data you have. I'll leave this open for a bit to let you come back but at the moment I'm thinking there's no way to offer what you're asking for.

**Comment by jstaffans-relex** [comment]
Yeah, I think that if `getFieldDisplayName` is used to map query results to yaml dataRefs it's probably not going to be possible to implement. There would need to be some other way to map the results, so that `getFieldDisplayName` could be instead used to fetch the text to display as the label. 

Still I think that allowing dataRefs like `$endpoint` which would reference a variable rather than a query result does have valid use cases. For example, if the SVG panel is repeated, you probably want to render some text to provide a unique identifier for each repetition. 

In my case I would like to create a kind of "data lineage" dashboard with 4-5 boxes indicating various storages and queues. I'd like to show hostnames or similar in each box. I can also display this in a table separate from the flow, but it would be much nicer to display it inline in the SVG panel. 

Also it would be nice to be able to reference variables in links, so that if I click an SVG element for e.g. a database instance, I am sent to a dashboard for that particular database instance. This would be similar to Grafana's [data links](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-data-links/).

**Comment by andymchugh** [comment]
Thanks for all the explanations; appreciate the time you've spent detailing it. In summary then:
- variable substitution is already available in links
- I'm going to add variable substitution to the valueMappings text. This will give you a way to display a variable value as a label either for all values of the time-series or you can change it based on different ranges.

I think that change, when published closes this out as changing the mapping from data-to-cell away from `getFieldDisplayName` isn't on the cards today. Does that meet give you enough to push ahead?

**Comment by jstaffans-relex** [comment]
>  Does that meet give you enough to push ahead?

Yes, that would be great!  👍

**Comment by andymchugh** [comment]
This is now published in version 1.13.0.

The valueMappings demonstration [dashboard](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboards/valueMappings.json) has been updated to demonstrate it.
