### ISSUE TITLE
Feature Request label/fill color valueMapping

### ISSUE THREAD

**Issue by netforce** [andymchugh/andrewbmchugh-flow-panel#64]
ability to use 'colorMapping' in the same way 'valueMappings' is implemented.

We would like to set the label of fill color based on the value without using the thresholds, because the values are set numers/errorcodes/whatever which might no be in correct numeral order to use thresholds, or even might be text instead of integers.

For example network interface states up/down/error/nan mapped to a specific color.

**Comment by andymchugh** [comment]
numbers have an order so if your incoming data is numerical you can get the color you want, you just have to order the thresholds from lower to higher. Threshold indexes don't have a meaning, just a traversal order.

will have a think about the string data. That as you say is unsupported.

**Comment by I558191** [comment]
+1 for basing the colors on string values.
the deprecated flowcharting plugin used to solve this by providing an input for color, pattern and level in the threshholds section.

**Comment by andymchugh** [comment]
This has been added using thresholds rather than mappings. Now in addition to thresholds and thresholdsRef there's also thresholdPatterns and thresholdPatternsRef. This is an [example use](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/stringDataThresholdPatterns.yaml#L77).

With this you can use a text data-series to drive labelColor, strokeColor and fillColor via regex.

It will be in the next build.

**Comment by andymchugh** [comment]
published in 1.14.0
